name: 'chicago_marathon'
version: '1.0.0'

profile: 'chicago_marathon'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  chicago_marathon:
    staging:
      +materialized: view

    marts:
      +materialized: table