version: 2

models:
  - name: mart_runner_results
    columns:
      - name: year
        data_tests:
          - not_null

      - name: finish_time_seconds
        data_tests:
          - not_null

      - name: race_date
        data_tests:
          - not_null