version: 2

models:
  - name: stg_results
    columns:
      - name: year
        data_tests:
          - not_null

      - name: gender
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - Man
                  - Woman
                  - Non-binary
                  - Not Specified

      - name: finish_time_seconds
        data_tests:
          - not_null

  - name: stg_weather
    columns:
      - name: year
        data_tests:
          - not_null
          - unique

      - name: race_date
        data_tests:
          - not_null